#config_version=6

#Clean up / customize /implement settings
#Add more chime sounds

config:
  - assets.yaml
  - coils.yaml
  - balldevices.yaml
  - displays.yaml
  - hardware.yaml
  - keyboard.yaml
  - lights.yaml
  - switches.yaml
  - widgetstyles.yaml
  - segmentdisplays.yaml
  - credits.yaml
  - sound.yaml
  - settings.yaml
  - variables.yaml
  - droptargets.yaml

modes:
# base modes
  - base
  - game
  - tilt
  - displays
  - service
  - service_dmd
  - credits
  - high_score
  - bonus
  - tilt
# additional modes
  - base_pops
  - base_rollovers
  - base_standups
  - base_drops
  - base_special
  - base_extraballs
  - base_chimer

custom_code:
  - custom_code.bonus_counter.BonusCounter
  - custom_code.drop_collector.DropCollector
  - custom_code.all_drop_watcher.AllDropWatcher

game:
  balls_per_game: settings.balls_per_game
  max_players: 2

#TODO For production, uncomment these items.
#logging:
#  console:
#    timers: none
#    event_manager: none
#  file:
#    timers: none
#    event_manager: none