#config_version=6

displays:
  window:
    width: 1200
    height: 565
    default: true

window:
  width: 1200
  height: 565
  title: "Roy Clarke The Entertainer"
  resizable: true
  borderless: false
  fullscreen: false
  exit_on_escape: true
  source_display: window