#config_version=6

sound_system:
  buffer: 2048
  channels: 1
  enabled: True
  frequency: 44100
  #master_volume: 0.8
  tracks:
    music:
      type: standard
      simultaneous_sounds: 1
      volume: .8
    voice:
      type: standard
      simultaneous_sounds: 1
      volume: 0.85
    sfx:
      type: standard
      simultaneous_sounds: 8
      volume: 0.8

sound_pools:
  song_pool:
    type: random_force_all
    track: music
    simultaneous_limit: 1
    sounds:
      - Yesterday
      - LiveWithMe
      - TipsOfMyFingers
      - RightOrLeft
      - OverAgain
      - Dream

sounds:
  Yesterday:
    track: music
    events_when_stopped: song_ended
  LiveWithMe:
    track: music
    events_when_stopped: song_ended
  TipsOfMyFingers:
    track: music
    events_when_stopped: song_ended
  RightOrLeft:
    track: music
    events_when_stopped: song_ended
  OverAgain:
    track: music
    events_when_stopped: song_ended
  Dream:
    track: music
    events_when_stopped: song_ended