#config_version=6

#This mode manages centralized handling for all display updates during a game.
mode:
  start_events: reset_complete
  events_when_started: displays_init_done
  priority: 5
  game_mode: false

segment_display_player:
  #Add players to displays when they are added to the game.
  player_added{num==1}:
    display_p1:
      text: "{players[0].score:d}"
      key: scores
      color: black
    display_p2:
      text: ""
      key: scores
      color: black
    display_credit:
      text: ""
      key: scores
      color: black
  player_added{num==2}:
    display_p2:
      text: "{players[1].score:d}"
      key: scores
      color: black

  #Remove scores when game ended.
  game_ended:
    display_p1:
      action: remove
      key: scores
    display_p2:
      action: remove
      key: scores
    display_credit:
      action: remove
      key: scores

  #Update scores when points are collected, and terminate flashing.
  player_score{player_num==1 and change>0}:
    display_p1:
      text: "{players[0].score:d}"
      action: no_flash
      key: scores
      color: black
  player_score{player_num==2 and change>0}:
    display_p2:
      text: "{players[1].score:d}"
      action: no_flash
      key: scores
      color: black

  #Flash displays when turns start.
  #player_turn_started{number==1}:
  ball_will_start{player==1}:
    display_p1:
      text: "{players[0].score:d}"
      action: flash
      key: scores
      color: black
  ball_will_start{player==2}:
    display_p2:
      text: "{players[1].score:d}"
      action: flash
      key: scores
      color: black