#config_version=6
tilt:
  multiple_hit_window: settings.multiple_hit_window
  settle_time: settings.settle_time
  warnings_to_tilt: settings.warnings_to_tilt

show_player:
  tilt_warning{current_player.tilt_warnings==1}:
    tilt_flash:
      loops: 0
  tilt_warning{current_player.tilt_warnings==2}:
    tilt_flash:
      loops: 1
  tilt:
    tilt_on:
      loops: -1
  tilt_clear:
    tilt_on:
      action: stop

shows:
  tilt_flash:
    - duration: 250ms
      lights:
        l_tilt: on
    - duration: 250ms
      lights:
        l_tilt: off
  tilt_on:
    - duration: 150ms
      lights:
        l_tilt: on

sound_player:
  tilt_warning{current_player.tilt_warnings==1}: beep
  tilt_warning{current_player.tilt_warnings==2}:
    beep:
      loops: 1
  tilt:
    beep:
      loops: 2